### ISSUE TITLE
EnOcean FT55 switch

### ISSUE THREAD

**Issue by Kroate** [kridgo/ha_enocean_custom#4]
I’m having trouble integrating my EnOcean FT55 light switches. The standard Home Assistant integration worked right away back then, but now, with the custom integration, I’m not receiving any signal.

Here is my configuration:
```

binary_sensor:
  - platform: enocean_custom
    id: [0xfe,0xe1,0xe5,0x1a]
    name: Lichtschalter_WZ2

  - platform: enocean_custom
    id: [0xfe,0xe1,0xe4,0xb4]
    name: Lichtschalter_BZ
    
  - platform: enocean_custom
    id: [0xfe,0xe1,0xe5,0x1d]
    name: Lichtschalter_OG

```

**Comment by kridgo** [comment]
Hi, that is strange.
Do you see if any packets are received by the dongle when you push the buttons? You could try activating debug logging for the integration. Put these lines in your `configuration.yaml`:
```
logger:
  default: info
  logs:
    custom_components.enocean_custom: debug
```
